id: P72C31DFC
initial_creation_type: input
source_metadata:
  title: Longchen Nyingtik Series
  language: de
  description: 'Texts related to the Longchen Nyingtik (klong chen snying thig, Heart
    Essence of the Vast Expanse) cycle revealed by Rigdzin Jigme Lingpa (1729/30–1798):'
  volume:
    b185019b3afb417e83cb4b56fc7f333f:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: Aspiration Prayers
    1d2e792585db4487b383549e89030725:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    f1a1bc47fa44410dafbc41535593dc35:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    bb2682d420654e979831b2c8193962f2:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Aspiration Prayers
    add5525a3df64be88d1fe545ae2cb779:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    b85190bff8ed4bf89ea612468f27e19d:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    8fe4903f803d463796bdacfff6747d4a:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Aspiration Prayers
    b85407de58ee4c19bddffdcd2d2c4f19:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: Commentaries
    7b1fe38bf82b4b81a5e222783d2decb2:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Commentaries
    c2c5b35e6d314c07b2c0e1b48c03cd8f:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    5bec94516a7d496e8b87ecc3562bf65e:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    429f978d791a414a8dee8fd4b4752e1d:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Commentaries
    8508db9f64304cf286f9d8a760554140:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    6f3f23d8fed24b21baf2193d7e385f63:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    c0aaf06522884e37a95bbcfe75959fc6:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    fe4dc5961774440da1037d1e2baea827:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Dukngal Rangdrol
    df3c64959e3b49b9bd233bfd17290fd1:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Dukngal Rangdrol
    3438963a4e3d473fbce9a9146fd29af7:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dukngal Rangdrol
    079017dc26a84778b6b0875d50c95a0f:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Dukngal Rangdrol
    c5063361a19e4f0f993349aeb287b714:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Dukngal Rangdrol
    9165a4478c3f4f4db7ac499e08435f77:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Dukngal Rangdrol
    adb110dd4d4e42fab7c8b2a041861479:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Dukngal Rangdrol
    7738047e429348a0a8c1c672eff973e5:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Dukngal Rangdrol
    80b6ac9b7cae4ddfad9bfa2260f6de49:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Dukngal Rangdrol
    bf5aaccf8ff64645823cdbc7ff57ccd0:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    9901599be41f4d3182e9bff1b55954c0:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment
    fb044f5dd3714aa2a3bb4b48de7027fd:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    e865f4017e8a485abbb96c3c1de86581:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    ddfab585f58443e292d01278e243066e:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    91cdd3c277894b62adc6e29edb26f821:
      title: Sādhana of the Great Master Vairotsana
      parent: Guru Yoga
    9f05709cedd649a8a4f4c1bd65d99c0f:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    9d1c4a216f8244f0a029eb4b30fee26d:
      title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the
        Heart Essence of the Vast Expanse from the Great Perfection'
      parent: Lineage Prayers
    5f41f4ad63c6456bb79d631d8b0cc7d1:
      title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
      parent: Lineage Prayers
    efea17a37659489087fd48eb2515286d:
      title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
      parent: Lineage Prayers
    c45d0b23556a4c24bfefd9410b6eb1e5:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    a582eed7bb6d4305afc5398755219d03:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    12e7e16595094a39b74d12b0a9528054:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    e5bb5e28ba164104a1c6434af0e50347:
      title: Supplement to the Longchen Nyingtik Lineage Prayer
      parent: Lineage Prayers
    203bebe5d04f4cb099750a04449bf3ad:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    5587e4262669452ea7bbc29fadb5962e:
      title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret
        Practice of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Lineage Prayers
    aa1fe7740ea9414e8479505303e7f601:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Lineage Prayers
    7da82efaeee343b4b2733024f9f8619c:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    cb67961cff624f92a1265bc0aa2a89ed:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    dc4a580e209543fe805a180d5b976171:
      title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence
        of the Vast Expanse
      parent: Lineage Prayers
    cec4e205806f4fa6a5993d6072bf2f35:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    844cb357314948cdad338a87a56c2e8c:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Ngöndro
    0cabeabe95ba46d6bcdc45a85ff5cea4:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Offerings
    e07e1fef102d4ff0a9593b845aaaeb3b:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Palchen Düpa
    c3873d95522c4124828c756cae9c3814:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Palchen Düpa
    af7a7fe24b734610a02bf9e1427b815f:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Palchen Düpa
    cee7db13d47144078f08c997ab5ca181:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Palchen Düpa
    a1ec98a062d440dcb49c0ae3a73ed2a3:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Palchen Düpa
    5d07b832d01e413693f4c8cc7c6b9450:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    a3d2eaad35f243abbc780b8d5c3dcf70:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    07ef40b0b96a4f4ebcda5a34dee71803:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Rigdzin Düpa
    5547ce4ba1db47168c658d2c7f6ae6e8:
      title: Rigdzin Düpa Amṛta Offering
      parent: Rigdzin Düpa
    151e06b2b60945bf841f28679f84c9bb:
      title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
      parent: Rigdzin Düpa
    e5a1b04b80584fe995c237ba6101084f:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Rigdzin Düpa
    3813577725464d068b2cb650822c88e1:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Rigdzin Düpa
    dc34721ce576478f9d724ca85160b989:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Rigdzin Düpa
    6c38b6939cbb498296007040468ab292:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Rigdzin Düpa
    ede88aa0f437409e8757585d0952bcd8:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Root Tantra
    3c06103cea4f4aec87e1f9b4a4e7f43b:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Sojong
    2479768d4a414d96a907bbf9e8ca352c:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Takhyung Barwa
    0f785c19dbb443999401481bf946add5:
      title: A Sādhana of Tārā Sarasvatī
      parent: Tārā
    a304e000c37444958dce0d88e5d98821:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Tārā
    181994b6a46547a2b35a5b0c7af72ab4:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    27d7ee16089c4656acc7821ee18d9161:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    34fb8fd893d14d2ebb698cac0202aabc:
      title: Notes on the Heart-Essence Practices of the Channels and Wind-Energies
      parent: Tsa Lung
    9fe8f89c6948422384bb5e6942cb11fa:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Tsok
    d382e4186cd54ca98ca32fa73c258896:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Tummo
    2cbcd64bbd76481ba30a724fb88e98f9:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Vajrasattva
    49b05ad0cfdd44eea819ab8ffe21c51b:
      title: 'Lamp That Illuminates the Excellent Path of Great Bliss: A Guide to
        the Practice Text of the Female Awareness-Holder, the Queen of Great Bliss'
      parent: Yumka Dechen Gyalmo
    0bc6c35a786941b8b1faf2605b07eef4:
      title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
        Female Practice'
      parent: Yumka Dechen Gyalmo
    d148b1620c1a43ff8a847bbb4d88b8f5:
      title: Yumka Fulfilment Practice
      parent: Yumka Dechen Gyalmo
    437c75e47b884bdf9aa08065a7b26185:
      title: 'The Lotus Garland: A Short Feast-Offering for the Female Practice of
        the Heart Essence of the Vast Expanse'
      parent: Yumka Dechen Gyalmo
    e603fc45b43d422ca8eb61fd01b28cd3:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Yumka Dechen Gyalmo
    c63178c19be144668a7b30bd7fec10a8:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Yumka Dechen Gyalmo
    a51e4f2b73a94c29b4e4be9b6bc0eadc:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    010d5391296749b8a8bcb6c53ffb5d9c:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    b288f7e2bd524e109e5457eead802d0f:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Yumka Dechen Gyalmo
    e296a1e28b4846bf8d50162ff6165513:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Yumka Dechen Gyalmo
    9919260fc2564c8cad41885d5fb6f10e:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Yumka Dechen Gyalmo
    121e06cccbb84a78a90d74b3a513c6b1:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Yumka Dechen Gyalmo
    62d8d8713ff247e080ad3f88caee362d:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Yumka Dechen Gyalmo
    35d96da81e8745b1befb793118ec6715:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Yumka Dechen Gyalmo
    1f054d8e0805469ba0d2404ab84aef20:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Yumka Dechen Gyalmo
created_at: '2022-03-01T04:26:19.166384'
last_modified_at: '2022-03-01T04:26:19.166387'
